import { jsPDF } from 'jspdf';
import { autoTable } from 'jspdf-autotable';
import type { ProcessedReport } from '../types/processed';

export interface PdfBranding { enabled:boolean; logoDataUrl?:string; heading:string; subheading:string; linkLabel:string; linkUrl:string; endPageText:string; themeColor:string; }
export interface PdfConfig { name:string; branding:PdfBranding; density:'comfortable'|'compact'; columnLimit:number; selectedColumns:string[]; }
const DEFAULT_BRANDING:PdfBranding={enabled:true,heading:'DocBit Report',subheading:'Prepared from your selected data',linkLabel:'Visit DocBit',linkUrl:'https://docbit.in',endPageText:'Generated with DocBit',themeColor:'#2563EB'};
export const defaultPdfConfig=(report:ProcessedReport):PdfConfig=>({name:'Monthly summary',branding:{...DEFAULT_BRANDING},density:'comfortable',columnLimit:Math.min(12,Math.max(8,report.columns.length)),selectedColumns:report.columns.filter(c=>c.settings?.trimWhitespace!==undefined).map(c=>c.key)});
function clean(v:unknown){return v===null||v===undefined||v===''?'—':String(v)}
function hexToRgb(hex:string){const m=hex.replace('#','').match(/^[0-9a-f]{6}$/i);if(!m)return [37,99,235] as const;return [parseInt(m[0].slice(0,2),16),parseInt(m[0].slice(2,4),16),parseInt(m[0].slice(4,6),16)] as const}

async function defaultLogoDataUrl(){try{const svg=await fetch('/favicon.svg').then(r=>r.text());const img=new Image();const src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject(new Error('logo'));img.src=src});const canvas=document.createElement('canvas');canvas.width=96;canvas.height=96;const ctx=canvas.getContext('2d');if(!ctx) return undefined;ctx.drawImage(img,0,0,96,96);return canvas.toDataURL('image/png')}catch{return undefined}}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export async function generatePdf(report:ProcessedReport, config:PdfConfig, fileName='DocBit-report.pdf'){
 const cols=report.columns.filter(c=>config.selectedColumns.includes(c.key)).slice(0,Math.max(4,Math.min(config.columnLimit,16)));
 const index=report.columns.reduce<Record<string,number>>((m,c,i)=>(m[c.key]=i,m),{}); const landscape=cols.length>8; const doc=new jsPDF({orientation:landscape?'landscape':'portrait',unit:'pt',format:'a4'}); const [r,g,b]=hexToRgb(config.branding.themeColor); const margin=30;
 const addHeader=()=>{doc.setDrawColor(r,g,b);doc.setLineWidth(2);doc.line(margin,42,doc.internal.pageSize.getWidth()-margin,42);doc.setFont('helvetica','bold');doc.setFontSize(18);doc.setTextColor(20,28,45);doc.text(config.branding.heading||'DocBit Report',margin,68);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(90,102,120);doc.text(config.branding.subheading||'',margin,84); if(config.branding.enabled&&defaultLogo){try{doc.addImage(defaultLogo,'PNG',doc.internal.pageSize.getWidth()-82,48,42,42)}catch{}}};
 const defaultLogo=config.branding.logoDataUrl || await defaultLogoDataUrl();
 const head=[cols.map(c=>c.displayName)]; const body=report.rows.map(row=>cols.map(c=>clean(row.values[index[c.key]])));
 autoTable(doc,{head,body,startY:102,margin:{left:margin,right:margin,top:30,bottom:48},styles:{font:'helvetica',fontSize:config.density==='compact'?6.5:7.5,cellPadding:config.density==='compact'?3:4,overflow:'linebreak',valign:'middle'},headStyles:{fillColor:[r,g,b],textColor:255,fontStyle:'bold',fontSize:config.density==='compact'?7:8},alternateRowStyles:{fillColor:[248,250,252]},didDrawPage:()=>{addHeader();const h=doc.internal.pageSize.getHeight();doc.setFontSize(7);doc.setTextColor(120,130,145);doc.text(`${config.branding.endPageText||'Generated with DocBit'}  •  Page ${doc.getNumberOfPages()}`,margin,h-20);}});
 let finalY=(doc as any).lastAutoTable?.finalY??102;
 if(report.groups?.length){for(const group of report.groups){if(finalY>doc.internal.pageSize.getHeight()-100){doc.addPage();addHeader();finalY=102}doc.setFont('helvetica','bold');doc.setFontSize(9);doc.setTextColor(r,g,b);doc.text(group.label||'Group',margin,finalY+20);finalY+=28;const rows=group.rows.map(row=>cols.map(c=>clean(row.values[index[c.key]])));autoTable(doc,{head:head,body:rows,startY:finalY,margin:{left:margin,right:margin,top:30,bottom:48},styles:{fontSize:config.density==='compact'?6.5:7.5,cellPadding:3,overflow:'linebreak'},headStyles:{fillColor:[r,g,b],textColor:255},didDrawPage:()=>addHeader()});finalY=(doc as any).lastAutoTable?.finalY??finalY;}}
 if(report.summaries.length){if(finalY>doc.internal.pageSize.getHeight()-100){doc.addPage();addHeader();finalY=102}doc.setFont('helvetica','bold');doc.setFontSize(10);doc.setTextColor(20,28,45);doc.text('Summary',margin,finalY+24);finalY+=34;autoTable(doc,{head:[['Calculation','Value']],body:report.summaries.map(s=>[s.label,s.displayValue]),startY:finalY,margin:{left:margin,right:margin},styles:{fontSize:8,cellPadding:4},headStyles:{fillColor:[r,g,b],textColor:255}})}
 if(config.branding.enabled&&config.branding.linkUrl){const pages=doc.getNumberOfPages();doc.setPage(pages);const h=doc.internal.pageSize.getHeight();doc.setFontSize(8);doc.setTextColor(r,g,b);doc.textWithLink(config.branding.linkLabel||config.branding.linkUrl,margin,h-34,{url:config.branding.linkUrl})}
 download(doc.output('blob'),fileName.endsWith('.pdf')?fileName:`${fileName}.pdf`);
}
