import React,{useEffect,useState} from 'react';
import {Camera,CheckCircle2,KeyRound,LogOut,Mail,Monitor,Shield,Trash2,UserRound} from 'lucide-react';
import {AppShell} from '../components/AppShell';import {Modal} from '../components/Modal';import {useAuth} from '../context/AuthContext';import {getPlan} from '../data/plans';import {deleteAccount,listSessions,removeSession,uploadProfilePhoto} from '../services/cloud';import {useToast} from '../hooks/useToast';
export function ProfilePage(){
 const {session,user,updateName,changePassword,resetPassword,signOut}=useAuth();const toast=useToast();const [name,setName]=useState(user?.displayName||'');const [photo,setPhoto]=useState(user?.photoURL||'');const [passwordOpen,setPasswordOpen]=useState(false);const [actionsOpen,setActionsOpen]=useState(false);const [confirmAction,setConfirmAction]=useState<'deactivate'|'delete'|null>(null);const [current,setCurrent]=useState('');const [next,setNext]=useState('');const [confirm,setConfirm]=useState('');const [busy,setBusy]=useState(false);const [sessions,setSessions]=useState<any[]>([]);
 useEffect(()=>{if(session)void listSessions(session).then(setSessions).catch(()=>undefined)},[session]);const plan=getPlan(user?.plan);
 async function save(){try{await updateName(name);toast.push('Profile saved','success')}catch(e){toast.push(e instanceof Error?e.message:'Profile could not be saved','error')}}
 async function photoChange(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(f.size>5*1024*1024){toast.push('Profile photo must be 5 MB or smaller','error');return;}try{setPhoto(await uploadProfilePhoto(session,f));toast.push('Profile photo updated','success')}catch(e){toast.push(e instanceof Error?e.message:'Photo could not be uploaded','error')}}
 async function password(){if(next!==confirm){toast.push('New passwords do not match','error');return}setBusy(true);try{await changePassword(current,next);setPasswordOpen(false);setCurrent('');setNext('');setConfirm('');toast.push('Password changed','success')}catch(e){toast.push(e instanceof Error?e.message:'Password could not be changed','error')}finally{setBusy(false)}}
 async function account(action:'deactivate'|'delete'){setBusy(true);try{await deleteAccount(session,action);await signOut()}catch(e){toast.push(e instanceof Error?e.message:'Account action failed','error')}finally{setBusy(false)}}
 return <AppShell><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><p className="text-sm font-medium text-blue-600">Account</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.04em]">Profile & Security</h1><p className="mt-2 text-sm text-slate-500">Manage your identity, security and active sessions.</p><div className="mt-8 grid gap-5 lg:grid-cols-[1fr_330px]"><div className="space-y-5">
 <section className="surface-card p-6"><h2 className="font-semibold">Profile</h2><div className="mt-6 flex items-center gap-5"><label className="relative block h-20 w-20 cursor-pointer"><div className="h-20 w-20 overflow-hidden rounded-3xl bg-blue-50 text-2xl font-bold text-blue-700">{photo?<img src={photo} alt="Profile" title="Profile" className="h-full w-full object-cover"/>:<span className="flex h-full w-full items-center justify-center">{name.slice(0,1).toUpperCase()||'D'}</span>}</div><span className="absolute -bottom-1 -right-1 flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-slate-900 text-white"><Camera size={14}/></span><input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={photoChange}/></label><div><p className="text-sm font-semibold">Profile photo</p><p className="mt-1 text-xs text-slate-500">PNG, JPG or WebP.</p></div></div><div className="mt-7 grid gap-4"><label className="field"><span>Full name</span><div className="field-wrap"><UserRound size={17}/><input value={name} onChange={e=>setName(e.target.value)}/></div></label><label className="field"><span>Email</span><div className="field-wrap"><Mail size={17}/><input value={user?.email||''} disabled/></div></label></div><button className="btn-primary mt-5" onClick={()=>void save()}>Save changes</button></section>
 <section className="surface-card p-6"><div className="flex items-center gap-2"><Shield size={17} className="text-blue-600"/><h2 className="font-semibold">Security</h2></div><div className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center gap-2 text-sm font-semibold"><CheckCircle2 size={15} className="text-emerald-600"/>Active account</div><p className="mt-1 text-xs text-slate-500">Your account is protected by password authentication and session controls.</p></div><div className="mt-4 flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>setPasswordOpen(true)}><KeyRound size={15}/>Change password</button><button className="btn-secondary" onClick={()=>void resetPassword(user?.email||'')}><KeyRound size={15}/>Forgot password</button></div></section>
 <section className="surface-card p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Sessions</h2><p className="mt-1 text-xs text-slate-500">Recent devices and sign-in locations.</p></div><Monitor size={18} className="text-slate-400"/></div><div className="mt-5 space-y-2">{sessions.length===0?<p className="text-sm text-slate-500">No recent session records.</p>:sessions.map(s=><div key={s.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-100"><Monitor size={16}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{[s.city,s.region,s.postal_code].filter(Boolean).join(', ')||'Location unavailable'} <span className="font-normal text-slate-400">| {s.browser}</span></p><p className="text-xs text-slate-400">{new Date(s.last_seen_at).toLocaleString()} · {s.device}{s.is_current?' · Current':''}</p></div><button className="text-xs font-semibold text-rose-600" onClick={async()=>{try{await removeSession(session,s.id);setSessions(x=>x.filter(v=>v.id!==s.id));toast.push('Device removed','success')}catch(e){toast.push(e instanceof Error?e.message:'Could not remove device','error')}}}>Remove Device</button></div>)}</div></section>
 <section className="surface-card border-rose-200 p-6"><h2 className="font-semibold text-rose-700">Danger zone</h2><p className="mt-1 text-xs leading-5 text-slate-500">Deactivate temporarily or permanently remove the account.</p><div className="mt-5 flex flex-wrap gap-2"><button className="btn-secondary text-amber-700" onClick={()=>{setActionsOpen(true)}}>Deactivate account</button><button className="btn-danger" onClick={()=>setActionsOpen(true)}><Trash2 size={15}/>Remove account</button></div></section>
 </div><aside className="space-y-5"><div className="surface-card p-6"><p className="text-xs font-bold uppercase tracking-[.12em] text-blue-600">Plan</p><h2 className="mt-2 text-2xl font-semibold">{plan.name}</h2><p className="mt-1 text-sm text-slate-500">{plan.monthlyPrice===0?'Free':'₹'+plan.monthlyPrice.toLocaleString('en-IN')+' / month'}</p></div><div className="surface-card p-6"><button className="flex w-full items-center justify-between rounded-xl border border-slate-200 px-4 py-3 text-sm font-medium" onClick={()=>void signOut()}>Sign out <LogOut size={15}/></button></div></aside></div></div>
 <Modal open={passwordOpen} onClose={()=>setPasswordOpen(false)} title="Change password" description="Enter your current password, then choose a new one." size="sm"><div className="grid gap-4"><label className="field"><span>Current Password</span><input className="input" type="password" value={current} onChange={e=>setCurrent(e.target.value)}/></label><label className="field"><span>New Password</span><input className="input" type="password" minLength={6} value={next} onChange={e=>setNext(e.target.value)}/></label><label className="field"><span>Confirm Password</span><input className="input" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="btn-primary justify-center" disabled={busy||!current||!next||!confirm} onClick={()=>void password()}>{busy?'Changing…':'Change password'}</button><button className="text-xs font-semibold text-blue-600" onClick={()=>void resetPassword(user?.email||'')}>Forgot password?</button></div></Modal>
 <Modal open={actionsOpen} onClose={()=>setActionsOpen(false)} title="Account actions" description="Choose what you want to do with your DocBit account." size="sm"><div className="grid gap-3"><button className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-left" onClick={()=>{setActionsOpen(false);setConfirmAction('deactivate')}}><p className="font-semibold text-amber-800">Deactivate Account</p><p className="mt-1 text-xs text-amber-700">Keep your data and recover it later.</p></button><button className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-left" onClick={()=>{setActionsOpen(false);setConfirmAction('delete')}}><p className="font-semibold text-rose-800">Remove Account</p><p className="mt-1 text-xs text-rose-700">Permanently remove your account and associated data.</p></button></div></Modal>
 <Modal open={!!confirmAction} onClose={()=>setConfirmAction(null)} title={confirmAction==='delete'?'Remove account':'Deactivate account'} description="Confirm this account action." size="sm"><p className="text-sm leading-6 text-slate-600">{confirmAction==='delete'?'This permanently deletes your account and data. This cannot be undone.':'Your projects and profile remain stored and can be recovered after you sign in again.'}</p><div className="mt-5 flex justify-end gap-2"><button className="modal-cancel-button-lg" onClick={()=>setConfirmAction(null)}>Cancel</button><button className={confirmAction==='delete'?'btn-danger':'btn-primary'} disabled={busy} onClick={()=>{const action=confirmAction;if(action){setConfirmAction(null);void account(action)}}}>{busy?'Please wait…':confirmAction==='delete'?'Remove account':'Deactivate account'}</button></div></Modal>
 </AppShell>}
