import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,Clock3,FolderKanban,Plus,UploadCloud,UsersRound,FileText,ShieldCheck} from 'lucide-react';
import {AppShell} from '../components/AppShell';
import {Dropzone} from '../components/Dropzone';
import {FileTypeIcon,fileTypeFromName} from '../components/FileTypeIcon';
import {navigate} from '../router/useRoute';
import {setPendingFile} from '../state/editorSession';
import {usePageMeta} from '../hooks/usePageMeta';
import {PAGE_META} from '../seo/pageMeta';
import {useAuth} from '../context/AuthContext';
import {listActivity,getUsage,listProjectFiles,listProjects,listWorkspaces,createWorkspace} from '../services/cloud';
import type {Activity,Project,ProjectFile,UsageSnapshot,Workspace} from '../types/cloud';
import {getPlan} from '../data/plans';
import {canProcess} from '../services/entitlements';
import {UpgradePlanModal} from '../components/UpgradePlanModal';

export function WorkspacePage(){
 const {user,session}=useAuth(); usePageMeta(PAGE_META['/workspace']); const plan=getPlan(user?.plan);
 const [workspaces,setWorkspaces]=useState<Workspace[]>([]); const [workspace,setWorkspace]=useState<Workspace|null>(null); const [projects,setProjects]=useState<Project[]>([]); const [activity,setActivity]=useState<Activity[]>([]); const [usage,setUsage]=useState<UsageSnapshot|null>(null); const [files,setFiles]=useState<ProjectFile[]>([]); const [q,setQ]=useState(''); const [error,setError]=useState(''); const [upgrade,setUpgrade]=useState<{title:string;description:string}|null>(null); const [creating,setCreating]=useState(false);
 const load=async()=>{if(!session)return;try{const ws=await listWorkspaces(session);setWorkspaces(ws);const current=ws[0]||null;setWorkspace(current);if(current&&typeof window!=='undefined')window.localStorage.setItem('docbit_workspace_id',current.id);const [ps,a,u]=await Promise.all([listProjects(session,current?.id),listActivity(session),getUsage(session)]);setProjects(ps);setActivity(a);setUsage(u);const all=await Promise.all(ps.slice(0,8).map(p=>listProjectFiles(session,p.id)));setFiles(all.flat())}catch(e){setError(e instanceof Error?e.message:'Workspace could not be loaded.')}};
 useEffect(()=>{void load()},[session]);
 const recent=useMemo(()=>{const needle=q.trim().toLowerCase();return activity.filter(a=>!needle||a.label.toLowerCase().includes(needle)).slice(0,8)},[activity,q]);
 const openFile=(file:File)=>{if(!user){navigate('/auth/login');return}if(usage&&!canProcess(user,usage)){setUpgrade({title:'Processing sessions used',description:`Your ${plan.name} plan includes ${plan.processingSessions?.toLocaleString()??'unlimited'} processing sessions per month. Upgrade to continue.`});return}if(file.size>plan.maxFileBytes){setUpgrade({title:'File size limit',description:`Your ${plan.name} plan supports files up to ${Math.round(plan.maxFileBytes/1024/1024)} MB.`});return}if(!file.size){setError('This file is empty.');return}setPendingFile(file);navigate(`/analyzing/${encodeURIComponent(file.name.replace(/\.[^.]+$/,''))}`)};
 const makeWorkspace=async()=>{if(!session)return;setCreating(true);try{const w=await createWorkspace(session,'New workspace');setWorkspaces(v=>[w,...v]);setWorkspace(w);if(typeof window!=='undefined')window.localStorage.setItem('docbit_workspace_id',w.id)}catch(e){setError(e instanceof Error?e.message:'Workspace could not be created.')}finally{setCreating(false)}};
 return <AppShell><div className="mx-auto max-w-7xl px-5 py-7 sm:px-8 sm:py-9"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold text-blue-600">{workspace?.name||'Workspace'}</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Start or continue data work.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Upload a file, continue a project, prepare the data, then export the result or create a report.</p></div><div className="flex gap-2"><select aria-label="Workspace" value={workspace?.id||''} onChange={e=>{const w=workspaces.find(x=>x.id===e.target.value)||null;setWorkspace(w);if(w&&typeof window!=='undefined')window.localStorage.setItem('docbit_workspace_id',w.id);if(session)void listProjects(session,w?.id).then(setProjects)}} className="input h-10 min-w-48 bg-white">{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select>{workspace?.role==='owner'&&<button className="btn-secondary" disabled={creating} onClick={()=>void makeWorkspace()}><Plus size={16}/>New workspace</button>}</div></div>
 <section className="surface-card mt-7 overflow-hidden border-blue-100"><div className="border-b border-slate-200 bg-white px-5 py-4"><div className="flex items-center gap-2"><UploadCloud size={18} className="text-blue-600"/><h2 className="font-semibold">Start a new processing session</h2></div><p className="mt-1 text-xs leading-5 text-slate-500">Upload Excel, CSV or JSON. Your source stays separate while you prepare a working result.</p></div><div className="p-5"><Dropzone onFile={openFile} maxFileSize={plan.maxFileBytes}/></div><div className="grid gap-3 border-t border-slate-100 bg-slate-50/70 p-4 sm:grid-cols-3"><div className="flex items-center gap-3"><FileTypeIcon type="excel" size={28}/><div><b className="text-xs">Excel</b><p className="text-[11px] text-slate-500">.xlsx / .xls</p></div></div><div className="flex items-center gap-3"><FileTypeIcon type="csv" size={28}/><div><b className="text-xs">CSV</b><p className="text-[11px] text-slate-500">Delimited tables</p></div></div><div className="flex items-center gap-3"><FileTypeIcon type="json" size={28}/><div><b className="text-xs">JSON</b><p className="text-[11px] text-slate-500">Structured records</p></div></div></div></section>
 <section className="mt-8 grid gap-4 lg:grid-cols-[1.4fr_.6fr]"><div className="surface-card p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Continue work</p><h2 className="mt-1 text-lg font-semibold">Recent projects</h2></div><button onClick={()=>navigate('/projects')} className="text-xs font-semibold text-blue-600">View all <ArrowRight size={13} className="inline"/></button></div><div className="mt-4 grid gap-2">{projects.slice(0,5).map(p=><button key={p.id} onClick={()=>navigate(`/projects/${p.id}`)} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3 text-left hover:border-blue-200 hover:bg-blue-50/40"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><FolderKanban size={17}/></span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{p.name}</b><small className="text-xs text-slate-400">{p.fileCount} files · updated {new Date(p.updatedAt).toLocaleDateString()}</small></span><ArrowRight size={15} className="text-slate-300"/></button>)}{projects.length===0&&<div className="rounded-xl border border-dashed border-slate-200 p-8 text-center"><FolderKanban className="mx-auto text-slate-300" size={28}/><p className="mt-2 text-sm text-slate-500">No projects yet.</p><button onClick={()=>navigate('/projects?create=1')} className="mt-3 text-xs font-semibold text-blue-600">Create your first project</button></div>}</div></div><div className="surface-card p-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Capacity</p><div className="mt-4 space-y-4"><Metric label="Projects" value={`${usage?.projects??0} / ${plan.projectLimit}`} pct={plan.projectLimit?((usage?.projects??0)/plan.projectLimit)*100:0}/><Metric label="Storage" value={`${((usage?.storageBytes??0)/1024/1024).toFixed(1)} MB / ${Math.round(plan.storageBytes/1024/1024)} MB`} pct={((usage?.storageBytes??0)/plan.storageBytes)*100}/><Metric label="Processing sessions" value={`${usage?.processingSessions??0} / ${plan.processingSessions??'∞'}`} pct={plan.processingSessions?((usage?.processingSessions??0)/plan.processingSessions)*100:0}/></div><button onClick={()=>navigate('/usage-plan')} className="btn-secondary mt-5 w-full justify-center">View usage</button></div></section>
 <section className="mt-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-semibold">Recent activity</h2><p className="text-xs text-slate-400">Meaningful project, file, processing and reporting events.</p></div><div className="search-box w-full sm:w-72"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search activity…"/></div></div><div className="mt-4 space-y-2">{recent.length===0?<div className="surface-card p-10 text-center"><Clock3 className="mx-auto text-slate-300" size={30}/><p className="mt-3 text-sm text-slate-500">No matching activity.</p></div>:recent.map(a=>{const f=files.find(x=>x.id===a.fileId);return <div key={a.id} className="activity-row cursor-pointer" onClick={()=>a.projectId&&navigate(`/projects/${a.projectId}`)}><span className="activity-icon">{f?<FileTypeIcon type={fileTypeFromName(f.originalName)} size={23}/>:<ShieldCheck size={17}/>}</span><span className="min-w-0 flex-1 text-left"><strong>{a.label}</strong><small>{new Date(a.createdAt).toLocaleString()}</small></span><ArrowRight size={15}/></div>})}</div></section>{error&&<div className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}</div><UpgradePlanModal open={!!upgrade} onClose={()=>setUpgrade(null)} title={upgrade?.title||'Upgrade your plan'} description={upgrade?.description||''}/></AppShell>
}
function Metric({label,value,pct}:{label:string;value:string;pct:number}){return <div><div className="flex justify-between gap-3 text-xs"><span className="font-medium text-slate-600">{label}</span><span className="text-slate-400">{value}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${Math.min(100,Math.max(0,pct))}%`}}/></div></div>}
