import React from 'react';
import { BarChart3, FolderKanban, Home, Settings, UserCircle, CreditCard, LogOut, UsersRound, Bell } from 'lucide-react';
import { navigate, useRoute } from '../router/useRoute';
import { getUsage, listWorkspaces } from '../services/cloud';
import { getPlan,formatStorage } from '../data/plans';
import { useToast } from '../hooks/useToast';
import { Logo } from './Logo';
import { useAuth } from '../context/AuthContext';

const nav=[{label:'Workspace',href:'/workspace',icon:Home},{label:'Projects',href:'/projects',icon:FolderKanban},{label:'Team',href:'/team',icon:UsersRound},{label:'Usage & Billing',href:'/usage-plan',icon:BarChart3},{label:'Plans',href:'/plans',icon:CreditCard}];
export function AppShell({children}:{children:React.ReactNode}){
 const [path]=useRoute(); const {user,session,loading,signOut}=useAuth(); const [profileOpen,setProfileOpen]=React.useState(false); const [headerStorage,setHeaderStorage]=React.useState(0); const [workspaces,setWorkspaces]=React.useState<import('../types/cloud').Workspace[]>([]); const [currentWorkspace,setCurrentWorkspace]=React.useState<import('../types/cloud').Workspace|null>(null); const plan=getPlan(user?.plan);
 React.useEffect(()=>{if(!loading&&!user)navigate('/auth/login')},[loading,user]);
 React.useEffect(()=>{if(!session)return;void getUsage(session).then(u=>setHeaderStorage(u.storageBytes)).catch(()=>undefined);void listWorkspaces(session).then(ws=>{setWorkspaces(ws);setCurrentWorkspace(v=>{const saved=typeof window!=='undefined'?window.localStorage.getItem('docbit_workspace_id'):null;const preferred=ws.find(x=>x.id===saved);if(preferred)return preferred;if(v&&ws.some(x=>x.id===v.id))return v;return ws[0]||null})}).catch(()=>undefined)},[session,path]);
 React.useEffect(()=>setProfileOpen(false),[path]);
 if(loading)return <div className="min-h-screen bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-10"><div className="skeleton h-8 w-32"/><div className="mt-10 skeleton h-64 w-full"/></div></div>; if(!user)return null;
 const initial=user.displayName?.slice(0,1).toUpperCase()||'D'; const usedPct=Math.min(100,headerStorage/plan.storageBytes*100);
 return <div className="min-h-screen bg-[#f6f8fb] text-slate-950">
 <aside className="fixed inset-y-0 left-0 z-40 hidden w-[244px] border-r border-slate-200 bg-white lg:flex lg:flex-col"><div className="flex h-[72px] items-center px-5"><Logo/></div><nav className="flex-1 px-3 py-5"><p className="px-3 pb-2 text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Workspace</p>{nav.map(item=>{const Icon=item.icon;const active=path===item.href||path.startsWith(`${item.href}/`);return <button key={item.href} onClick={()=>navigate(item.href)} className={`app-nav ${active?'app-nav-active':''}`}><Icon size={18}/><span>{item.label}</span></button>})}</nav><div className="border-t border-slate-200 p-3"><button onClick={()=>navigate('/settings')} className={`app-nav ${path==='/settings'?'app-nav-active':''}`}><Settings size={18}/><span>Settings</span></button><button onClick={()=>void signOut()} className="app-nav text-slate-500"><LogOut size={18}/><span>Sign out</span></button></div></aside>
 <div className="lg:pl-[244px]"><header className="sticky top-0 z-30 flex h-[64px] items-center justify-between border-b border-slate-200/80 bg-white/90 px-5 backdrop-blur-xl sm:px-8"><div className="lg:hidden"><Logo/></div><div className="hidden min-w-0 flex-1 items-center gap-3 lg:flex"><select aria-label="Current workspace" value={currentWorkspace?.id||''} onChange={e=>{const w=workspaces.find(x=>x.id===e.target.value)||null;setCurrentWorkspace(w);if(w&&typeof window!=='undefined')window.localStorage.setItem('docbit_workspace_id',w.id);navigate('/workspace')}} className="input h-9 max-w-52 bg-white text-xs font-semibold">{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><div className="relative h-9 w-9 shrink-0"><svg viewBox="0 0 36 36" className="h-9 w-9 -rotate-90"><circle cx="18" cy="18" r="15" fill="none" stroke="currentColor" strokeWidth="3" className="text-slate-100"/><circle cx="18" cy="18" r="15" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" className="text-blue-600" strokeDasharray="94.25" strokeDashoffset={94.25*(1-usedPct/100)}/></svg><span className="absolute inset-0 flex items-center justify-center text-[8px] font-bold text-slate-600">{Math.round(usedPct)}%</span></div><div><p className="text-xs font-semibold text-slate-700">Storage</p><p className="text-[11px] text-slate-500">{formatStorage(headerStorage)} / {formatStorage(plan.storageBytes)}</p></div><button onClick={()=>navigate('/usage-plan')} className="text-xs font-semibold text-blue-600 hover:text-blue-700">View usage</button></div><div className="relative flex items-center gap-2"><button className="icon-button header-icon-button" aria-label="Notifications" title="Notifications"><Bell size={18}/></button><div className="relative"><button onClick={()=>setProfileOpen(v=>!v)} className="avatar-button" aria-label="Profile menu" aria-expanded={profileOpen} title="Profile">{user.photoURL?<img src={user.photoURL} alt="Profile" title="Profile" className="h-full w-full rounded-full object-cover"/>:initial}</button>{profileOpen&&<div className="profile-dropdown"><button onClick={()=>navigate('/profile')}><UserCircle size={16}/>Profile</button><button onClick={()=>navigate('/settings')}><Settings size={16}/>Settings</button><button onClick={()=>void signOut()}><LogOut size={16}/>Sign out</button></div>}</div></div></header><main className="min-h-[calc(100vh-64px)] pb-24 lg:pb-0">{children}</main></div>
 <nav className="mobile-bottom-nav lg:hidden">{nav.slice(0,4).map(item=>{const Icon=item.icon;const active=path===item.href||path.startsWith(`${item.href}/`);return <button key={item.href} onClick={()=>navigate(item.href)} className={active?'mobile-nav-active':''}><Icon size={19}/><span>{item.label==='Usage & Billing'?'Usage':item.label}</span></button>})}</nav></div>;
}
