import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Download,FileText,Link2,Palette,Save,ShieldCheck,UploadCloud} from 'lucide-react';
import {Modal} from './Modal';import {GlobalSelect} from './GlobalSelect';
import {UpgradePlanModal} from './UpgradePlanModal';
import {defaultPdfConfig,generatePdf,type PdfConfig} from '../pdf/generatePdf';
import type {ProcessedReport} from '../types/processed';
import type {PdfConfiguration} from '../types/cloud';
import {useAuth} from '../context/AuthContext';
import {getPlan} from '../data/plans';
import {savePdfConfiguration} from '../services/cloud';
import {useToast} from '../hooks/useToast';

export function PdfGenerationModal({open,onClose,report,fileName,projectId,role='owner',savedConfigs=[]}:{open:boolean;onClose:()=>void;report:ProcessedReport;fileName:string;projectId?:string;role?:'owner'|'editor'|'member';savedConfigs?:PdfConfiguration[]}){
 const {session,user}=useAuth(); const toast=useToast(); const plan=getPlan(user?.plan); const [step,setStep]=useState<'enable'|'warning'|'branding'|'ready'>('enable'); const [branding,setBranding]=useState(false); const [cfg,setCfg]=useState<PdfConfig>(()=>defaultPdfConfig(report)); const [upgrade,setUpgrade]=useState(false); const [busy,setBusy]=useState(false);
 const wide=report.columns.length>12 || report.columns.some(c=>c.displayName.length>32); const tooMuch=report.columns.length>12 || report.rows.some(r=>r.values.some(v=>String(v??'').length>220)); const effective=useMemo(()=>({...cfg,branding:{...cfg.branding,enabled:true,heading:branding?cfg.branding.heading:'DocBit Report',subheading:branding?cfg.branding.subheading:'Prepared from your selected data',linkLabel:branding?cfg.branding.linkLabel:'Visit DocBit',linkUrl:branding?cfg.branding.linkUrl:'https://docbit.in',endPageText:branding?cfg.branding.endPageText:'Generated with DocBit',themeColor:branding?cfg.branding.themeColor:'#2563EB'}}),[cfg,branding]);
 useEffect(()=>{if(open){setStep('enable');setCfg(defaultPdfConfig(report));setBranding(false)}},[open,report]);
 const enable=()=>{if(tooMuch||wide)setStep('warning');else setStep('branding')};
 const chooseBranding=(next:boolean)=>{if(next&&plan.id==='free'){setUpgrade(true);return}setBranding(next);setStep('branding')};
 const logo=(file:File)=>{if(file.size>1024*1024){toast.push('Logo must be 1 MB or smaller.','error');return}const reader=new FileReader();reader.onload=()=>setCfg(c=>({...c,branding:{...c.branding,logoDataUrl:String(reader.result||'')}}));reader.readAsDataURL(file)};
 const generate=async()=>{setBusy(true);try{await generatePdf(report,effective,fileName.replace(/\.[^.]+$/,'')+'-summary.pdf');toast.push('PDF generated and downloaded','success');onClose()}catch(e){toast.push(e instanceof Error?e.message:'PDF could not be generated','error')}finally{setBusy(false)}};
 const save=async()=>{if(!session||!projectId)return;setBusy(true);try{await savePdfConfiguration(session,projectId,cfg.name,effective);toast.push('Report template saved','success')}catch(e){toast.push(e instanceof Error?e.message:'Report template could not be saved','error')}finally{setBusy(false)}};
 const title=step==='enable'?'Enable PDF generation':step==='warning'?'PDF data check':step==='branding'?'PDF branding':'Generate PDF';
 return <><Modal open={open} onClose={onClose} title={title} description="Create a clean, project-ready PDF without exposing unnecessary source fields." size="md" footer={step==='enable'?<div className="flex justify-end"><button className="btn-primary" onClick={enable}>Enable PDF generation</button></div>:step==='warning'?<div className="flex justify-end gap-2"><button className="modal-cancel-button-lg" onClick={onClose}>Cancel</button><button className="btn-primary" onClick={()=>setStep('branding')}>Ignore alert and continue</button></div>:step==='branding'?<div className="flex justify-end gap-2"><button className="modal-cancel-button-lg" onClick={()=>setStep('enable')}>Back</button><button className="btn-primary" onClick={()=>setStep('ready')}>Continue</button></div>:<div className="flex flex-wrap justify-end gap-2"><button className="btn-secondary" disabled={busy||role==='member'||!projectId} onClick={()=>void save()}><Save size={15}/>Save report template</button><button className="btn-primary" disabled={busy} onClick={()=>void generate()}><Download size={15}/>{busy?'Generating…':'Generate and download PDF'}</button></div>}>
 {step==='enable'&&<div className="grid gap-4"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="flex items-start gap-3"><FileText className="mt-0.5 text-blue-600" size={22}/><div><p className="font-semibold">A presentation layer for project users</p><p className="mt-1 text-sm leading-6 text-slate-600">PDF generation creates a separate summary from the current report. It does not alter the original Excel, CSV or JSON file.</p></div></div></div><div className="grid gap-2 sm:grid-cols-3"><Info icon={<ShieldCheck size={16}/>} title="Private source" text="Only selected report fields are rendered."/><Info icon={<FileText size={16}/>} title="Multi-page" text="Rows continue across pages."/><Info icon={<Palette size={16}/>} title="Premium layout" text="Wide tables adapt to landscape."/></div></div>}
 {step==='warning'&&<div className="grid gap-4"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex gap-3"><AlertTriangle className="text-amber-600" size={21}/><div><p className="font-semibold text-amber-950">This report is wide or contains large cell content.</p><p className="mt-1 text-sm leading-6 text-amber-900/80">The PDF will prioritize the first {Math.min(cfg.columnLimit,16)} selected columns. Rows are not truncated; they continue onto additional pages.</p></div></div></div><p className="text-xs text-slate-500">Detected {report.columns.length} columns and {report.rows.length.toLocaleString()} report rows.</p></div>}
 {step==='branding'&&<div className="grid gap-4"><label className="flex items-center justify-between rounded-xl border border-slate-200 p-4"><div><p className="text-sm font-semibold">Enable branding</p><p className="text-xs text-slate-500">Logo, heading, link, end-page text and theme color.</p></div><input type="checkbox" checked={branding} disabled={plan.id==='free'} onChange={e=>chooseBranding(e.target.checked)} /></label>{branding&&<div className="grid gap-3 rounded-2xl border border-slate-200 p-4"><label className="field"><span>Logo</span><div className="flex gap-2"><label className="btn-secondary cursor-pointer"><UploadCloud size={15}/>Upload logo<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)logo(f)}}/></label>{cfg.branding.logoDataUrl&&<span className="flex items-center text-xs text-slate-500">Logo selected</span>}</div></label><label className="field"><span>Heading</span><input className="input" value={cfg.branding.heading} onChange={e=>setCfg(c=>({...c,branding:{...c.branding,heading:e.target.value}}))}/></label><label className="field"><span>Subheading</span><input className="input" value={cfg.branding.subheading} onChange={e=>setCfg(c=>({...c,branding:{...c.branding,subheading:e.target.value}}))}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="field"><span>Link label</span><input className="input" value={cfg.branding.linkLabel} onChange={e=>setCfg(c=>({...c,branding:{...c.branding,linkLabel:e.target.value}}))}/></label><label className="field"><span>Link URL</span><div className="field-wrap"><Link2 size={15}/><input value={cfg.branding.linkUrl} onChange={e=>setCfg(c=>({...c,branding:{...c.branding,linkUrl:e.target.value}}))}/></div></label></div><label className="field"><span>End page text</span><input className="input" value={cfg.branding.endPageText} onChange={e=>setCfg(c=>({...c,branding:{...c.branding,endPageText:e.target.value}}))}/></label><label className="field"><span>Theme color</span><input type="color" value={cfg.branding.themeColor} onChange={e=>setCfg(c=>({...c,branding:{...c.branding,themeColor:e.target.value}}))} className="h-10 w-16 rounded-lg border border-slate-200 p-1"/></label></div>}{!branding&&<div className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-xs text-slate-600">Default DocBit branding will be used. {plan.id==='free'&&<button type="button" className="ml-1 font-semibold text-blue-600" onClick={()=>setUpgrade(true)}>Upgrade to customize.</button>}</div>}</div>}
 {step==='ready'&&<div className="grid gap-4">{savedConfigs.length>0&&<label className="field"><span>Saved PDF configuration</span><GlobalSelect value="" onChange={value=>{const found=savedConfigs.find(x=>x.id===value);if(found&&found.config)setCfg({...cfg,...found.config,branding:{...cfg.branding,...(found.config.branding||{})}})}} title="Saved PDF configuration" options={[{value:'',label:'Current configuration'},...savedConfigs.map(x=>({value:x.id,label:x.name}))]}/></label>}<div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm font-semibold">Ready to generate</p><p className="mt-1 text-sm text-slate-500">{report.rows.length.toLocaleString()} rows · {Math.min(cfg.columnLimit,16)} columns · {branding?'Custom branding':'DocBit branding'}</p></div><div className="grid gap-2 sm:grid-cols-2"><Info icon={<Download size={16}/>} title="Generate & download" text="Creates the PDF locally in your browser."/><Info icon={<Save size={16}/>} title="Save configuration" text={role==='member'?'Users can generate but cannot save configuration.':'Save this PDF setup to the project.'}/></div></div>}
 </Modal><UpgradePlanModal open={upgrade} onClose={()=>setUpgrade(false)} title="Upgrade for PDF branding" description="PDF branding is available on paid plans. You can still generate one-off PDFs on every plan."/></>;
}
function Info({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-xl border border-slate-200 bg-white p-3"><div className="flex items-center gap-2 text-sm font-semibold">{icon}{title}</div><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div>}
