import React, { useEffect, useState } from 'react';
import { FolderKanban, Plus } from 'lucide-react';
import { Modal } from './Modal';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../hooks/useToast';
import { createProject, listProjects, listProjectFiles, saveProjectFile } from '../services/cloud';
import type { Project, ProjectFile } from '../types/cloud';
import type { DocumentState } from '../types/document';

export function SaveToProjectModal({open,onClose,document,file,existing,onSaved}:{open:boolean;onClose:()=>void;document:DocumentState;file:File;existing?:{project:Project;file:ProjectFile}|null;onSaved:(project:Project,file:ProjectFile)=>void}){
 const {session}=useAuth(); const toast=useToast();const [projects,setProjects]=useState<Project[]>([]);const [selected,setSelected]=useState('');const [newName,setNewName]=useState('');const [creating,setCreating]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{if(!open||!session)return;void listProjects(session).then(p=>{setProjects(p.filter(x=>x.accessRole!=='member'));setSelected(existing?.project.id||p.find(x=>x.accessRole!=='member')?.id||'')}).catch(e=>setError(e instanceof Error?e.message:'Projects could not be loaded.'))},[open,session,existing?.project.id]);
 const save=async()=>{if(!session)return;setBusy(true);setError('');try{let project=projects.find(p=>p.id===selected);if(!project){if(!newName.trim())throw new Error('Choose a project or create one.');project=await createProject(session,newName);setProjects(p=>[project!,...p]);}if(!existing){const existingFiles=await listProjectFiles(session,project.id);if(existingFiles.some(x=>x.originalName.toLowerCase()===file.name.toLowerCase())){throw new Error('This file already exists in this project.')}}const saved=await saveProjectFile(session,project,file,document,existing?.file);onSaved(project,saved);onClose();}catch(e){const msg=e instanceof Error?e.message:'File could not be saved.';setError(msg);if(/already exists/i.test(msg))toast.push('File already exists in this project.','info')}finally{setBusy(false)}};
 return <Modal open={open} onClose={onClose} title={existing?'Save changes':'Add to project'} description={existing?`Save your latest changes to ${existing.file.originalName}.`:'Choose where this file should live.'} size="sm" footer={<div className="flex justify-end gap-2"><button onClick={onClose} className="modal-cancel-button-lg">Cancel</button><button onClick={()=>void save()} disabled={busy||(!selected&&!newName.trim())} className="btn-primary disabled:opacity-50">{busy?'Saving…':existing?'Save changes':'Add to project'}</button></div>}><div className="grid gap-5"><div><p className="field-label">Project</p>{projects.length?<div className="mt-2 grid gap-2">{projects.map(p=><button key={p.id} onClick={()=>{setSelected(p.id);setNewName('')}} className={`flex items-center gap-3 rounded-xl border p-3 text-left ${selected===p.id?'border-blue-500 bg-blue-50':'border-slate-200 bg-white hover:bg-slate-50'}`}><span className="project-icon"><FolderKanban size={16}/></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{p.name}</strong><small className="text-xs text-slate-500">{p.fileCount} files</small></span></button>)}</div>:<p className="mt-2 text-sm text-slate-500">No projects yet. Create one below.</p>}</div><div className="border-t border-slate-200 pt-5"><p className="field-label">Create a new project</p><div className="mt-2 flex gap-2"><input className="input" value={newName} onChange={e=>{setNewName(e.target.value);setSelected('')}} placeholder="Project name"/><button onClick={()=>setNewName(newName.trim())} className="btn-secondary" title="Use new project"><Plus size={16}/></button></div></div>{error&&<p className="text-sm text-rose-600">{error}</p>}</div></Modal>
}
